# -*- coding: utf-8 -*-
"""CLASS LIBRARY BOOTCAMP  .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VAFKNdSqdTl24MOCMkspoQ--wGt40pvw
"""

class Library:

   def __init__(self):
      self.file=open("books.txt","a+")

   def __del__(self):
      self.file.close()

   def list_books(self):
       self.file=open("books.txt","r")
       all_content=self.file.readlines()
       if len(all_content)==0:
         print("Library is empty, no books to show.")
       else:
         self.file=open("books.txt","r")
         i=1
         for line in self.file:
             line=line.split(",")
             print(str(i),") ","Book Title: ",line[0].upper(),","," Author of the Book: ",line[1].upper())
             i+=1

   def add_book(self):
       self.title=input("Please enter the title of the book. ").upper()
       self.author=input("Please enter the author of the book. ").upper()
       self.year=input("Please enter the first release year of the book. ").upper()
       self.number_of_pages=input("Please enter the number of pages. ").upper()
       x=self.title+"," +self.author +","+self.year +","+self.number_of_pages
       self.file=open("books.txt","a+")
       self.file.write(x+"\n")
       self.file.seek(0)

   def remove(self):
        book=input("Which book do you want to delete? ").upper()
        with open("books.txt","r") as self.file:
            content=self.file.readlines()
            book_name_list=[line.split(",")[0] for line in content]
            count=book_name_list.count(book)
            if count==1:
               self.file=open("books.txt","w")
               for line in content:
                  x=line.split(",")
                  if x[0].upper()!=book:
                     self.file.write(line)
               self.file.seek(0)
               print("Book deleted")
            elif count>1:
               author_list= [line.split(",")[1] for line in content]
               author=input("There is more than one book with the same name.\nPlease enter the author of the book. ").upper()
               count_author=author_list.count(author)
               if count_author==1:
                        self.file=open("books.txt","w")
                        for line in content:
                           x=line.split(",")
                           if x[1].upper()!=author:
                              self.file.write(line)
                        self.file.seek(0)
                        print("Book deleted")
               else:
                        self.file=open("books.txt","w")
                        for line in content:
                           x=line.split(",")
                           if x[0].upper()!=book or (x[0].upper()==book and x[1].upper()!=author):
                              self.file.write(line)
                        self.file.seek(0)
                        print("Book deleted")
            elif book_name_list==[]:
               print("Library is empty,you cannot delete the book!")
            else:
               print("This book is not available in the library.")
lib=Library()
while True:
    print("\n*****MENU*****\n"
           "1) LIST BOOKS\n"
           "2) ADD BOOK\n"
           "3) REMOVE BOOK\n"
           "Press Q to exit")
    choice= input("Please choose one of the actions.")
    if choice==str(1):
       lib.list_books()
    elif choice==str(2):
       lib.add_book()
    elif choice==str(3):
       lib.remove()
    elif choice.upper()=="Q":
       print("EXIT")
       break
    else:
       print("Please make sure you press the right button.")





